name: Infrastructure CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  terraform-ci:
    name: Terraform Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Inject Dummy Token Variable
        run: echo 'variable "do_token" { default = "DUMMY" }' > dummy.tf

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (Backend Disabled)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: TFLint Setup
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run tflint
        run: tflint --init && tflint
