name: PR Template Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Body for Required Fields
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";

            const requiredSections = {
              "Jira Ticket": /\[([A-Z]+-\d+)\]\(https:\/\/sefire\.atlassian\.net\/browse\/[A-Z]+-\d+\)/,
              "Summary - What": /\*\*What:\*\*\s*\n(?!<!--)(?!\s*-->).+/,
              "Summary - Why": /\*\*Why:\*\*\s*\n(?!<!--)(?!\s*-->).+/,
              "Summary - How": /\*\*How:\*\*\s*\n(?!<!--)(?!\s*-->).+/,
              "Notable Commits Table": /\| Commit Type\s+\| SHA Link\s+\| Note For Reviewer \|/,
              "Checklist": /- \[x\] Terraform Plan successful/i
            };

            const failures = Object.entries(requiredSections).filter(([name, pattern]) => !pattern.test(body));

            if (failures.length > 0) {
              const messages = failures.map(([name]) => `❌ Missing or incomplete section: **${name}**`);
              core.setFailed(messages.join("\n"));
            } else {
              console.log("✅ All required PR sections are properly filled.");
            }
